apiVersion: v1
kind: Service
metadata:
  name: my-service-for-node-web-app
spec:
  type: LoadBalancer
  selector:
    app: node-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
